
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: flexable_development

test:
  <<: *default
  database: flexable_test

production:
  <<: *default
  database: flexable_production
  username: flexable
  password: <%= ENV['FLEXABLE_DATABASE_PASSWORD'] %>
